### ISSUE TITLE
how to get repos for a specific user ?

### ISSUE THREAD

**Issue by mayuroks** [pksunkara/octonode#121]
I cudnt find any method like ghuser.repos() to get repos for a particular user

Also using this method

``` javascript
var client = github.client();

client.get('/users/visionmedia/repos', {}, function (err, status, body, headers) {
  console.log(body); //json object
});
```

I get only 30 repos . I understand its bcoz of pagination. Can you suggest a way to insert pagination options in the above client.get() call ??

**Comment by kevinSuttle** [comment]
https://developer.github.com/v3/repos/#list-user-repositories

**Comment by kevinSuttle** [comment]
https://developer.github.com/v3/#link-header You can use 'since' and specify the amount.
