### ISSUE TITLE
Authenticate to github in web mode (web application) - Possible Documentation Error

### ISSUE THREAD

**Issue by iwozzy** [pksunkara/octonode#163]
In this part: 
```javascript
if (uri.pathname=='/login') {
    res.writeHead(301, {'Content-Type': 'text/plain', 'Location': auth_url})
    res.end('Redirecting to ' + auth_url);
  }
```
I'm trying this out with Express and found that when I use 301 status code, the auth_url (along with the state) is cached. It therefore doesn't work with the CSRF check.

Using the 302 status code solves the issue.

**Comment by pksunkara** [comment]
Thanks for the info. I will update the README.
