### ISSUE TITLE
There is an error message on empty repository

### ISSUE THREAD

**Issue by iwozzy** [pksunkara/octonode#171]
Github returns the following when a repository has no commits 

`{
  "message": "Git Repository is empty.",
  "documentation_url": "https://developer.github.com/v3"
}`

The library currently returns an error like this

`Error: Repo commits error`

You can see this here https://api.github.com/repos/errfree/test/commits

I'm not sure what the best solution is, but it seems that the library error is ambiguous. I'm also not sure if this is the only case this error message will be returned..

**Comment by pksunkara** [comment]
Yes. This is an intended behaviour. Any api call that returns `4xx` or `5xx` will generate an error. If you want to have more control on this, I recommend that you use `client.get`, `client.post` etc.. directly.
