### ISSUE TITLE
Strategy for connecting to all requests

### ISSUE THREAD

**Issue by jeffwilcox** [pksunkara/octonode#172]
Hi,
I'm looking to brainstorm with someone about how to best hook into the request pipeline for the module. I want to track in a single place the rate limits sitting around from the request headers; although I can easily plumb this into every place that I'm calling Octonode functions, it seems like there might be a better way - I'm just not smart enough to think of what that is right now.

And ideas would be great.

Essentially I want to be able to present a reasonable rate remaining piece of data inside some web pages that users are using, to give them an idea of how hard they're hitting the API service, etc.

Thanks,
Jeff

**Comment by pksunkara** [comment]
Hey @jeffwilcox 

I am sorry but there is no way to pipe the request currently. Although you can add support for it easily in `src/octonode/client.coffee`. I welcome any contributions.
