### ISSUE TITLE
Deleting labels with unicode characters

### ISSUE THREAD

**Issue by mal** [pksunkara/octonode#176]
Can fetch them fine, but calling delete results in a 404 :(

**Comment by mal** [comment]
Example character `✔︎`

**Comment by pksunkara** [comment]
Are you sure its not an issue with github?

**Comment by mal** [comment]
No, but I'm not sure the best way to find out either.

**Comment by pksunkara** [comment]
Can you try using CURL from the command line?

**Comment by mal** [comment]
Ok, I'll give it a try when I can, script went a bit mad and has exceeded the rate limit for now u__u

**Comment by mal** [comment]
So I can delete them fine with curl so long as I `encodeURI` the label name.

```
curl -i -XDELETE 'https://api.github.com/repos/mal/repo/labels/mal%20%EE%90%A7
HTTP/1.1 204 No Content
Server: GitHub.com
...
```

**Comment by pksunkara** [comment]
hmm.. So, I guess octonode should `encodeURI` stuff. Thanks :)

**Comment by pksunkara** [comment]
Fixed in master
