### ISSUE TITLE
Updating a file with content encoded / not encoded

### ISSUE THREAD

**Issue by enjareyes** [pksunkara/octonode#178]
Trying to send code to update a file in a repo, but when I encode it it shows up encoded on the repo. When I don't encode it in b64 it only works with tiny files and crashes when it's a larger file. I realize it needs to be encoded content somehow, but can't see how to do it using octonode: 

current code: 

  var path = req.body.path,
      message = req.body.message,
      sha=req.body.sha,
      encodedContent = req.body.encoded, 
      content = req.body.content;

  var client = github.client(req.session.token);
  var ghrepo = client.repo(repo)

  ghrepo.updateContents(path, message, content, sha, 
  function(err, resp, body){
    if (err) console.log(err)
    else {
      res.sendStatus(200)
    }
  })

**Comment by joshrp** [comment]
Had a quick dig and it looks like Octonode is doing the encoding for you here: https://github.com/pksunkara/octonode/blob/master/lib/octonode/repo.js#L408

As for the larger file size I'll have a poke around but that sounds like an issue

**Comment by enjareyes** [comment]
This is the app being worked on if you want to see. 
https://code-colab.herokuapp.com/

When I edit an empty readme and add 'hello' it works just fine, but when I try it on a normal repo with larger amounts of code in it (not an insane amount) it doesn't work- I'm seeing this in the console: 
POST https://code-colab.herokuapp.com/api/repos/commit 503 (Service Unavailable)

**Comment by enjareyes** [comment]
Server is throwing this error: Repo updateContents error

**Comment by joshrp** [comment]
Sounds a lot more like a server problem not handling the file update correctly. Looks like the request is going off OK if you can verify the headers?

**Comment by enjareyes** [comment]
I found what was breaking that call and fixed it, it was just an issue with the filepath; however, I'm trying to update a file on a specific branch and there is no param that allows for it. On git they allow for it, but how would I include the branch specification using Octonode? It's in the 'update a file' section.
https://developer.github.com/v3/repos/contents/#update-a-file

My code: 
ghrepo.updateContents(path, message, content, sha, <BRANCH_HERE?>
  function(err, resp, body){
    if (err) console.log(err, resp, body)
    else {
      res.sendStatus(200)
    }
  })

**Comment by joshrp** [comment]
Looking at https://github.com/pksunkara/octonode/blob/master/lib/octonode/repo.js#L400, you should be able to add the branch name between `content` and `sha` in your example call you posted.

**Comment by enjareyes** [comment]
I added the branch right after sha / before the callback and it worked- submitted a pull request to your git readme in case anyone else had the same question :) Thank you so much for responding so quickly!

**Comment by joshrp** [comment]
Ooops, that's what I meant. 

No problem, glad it's working

**Comment by pksunkara** [comment]
I would have replied but @joshrp is not giving me any time :smiley:
