### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by benweet** [pksunkara/octonode#186]
Getting this issue when network connection is down:

```
node_modules/octonode/lib/octonode/auth.js:111
            if (res.statusCode === 404) {
                   ^
TypeError: Cannot read property 'statusCode' of undefined
```

I guess you want to check that `err` is empty before reading `res`.
Let me know if you want a PR.

**Comment by pksunkara** [comment]
Yes please. https://github.com/pksunkara/octonode/blob/master/src/octonode/auth.coffee#L91.
