### ISSUE TITLE
Request Ability to Specify GitHub Server

### ISSUE THREAD

**Issue by ResidentBiscuit** [pksunkara/octonode#207]
To use this in an enterprise environment, the ability to specify the GitHub server to use would be great.

**Comment by uny** [comment]
Not documented, but you can.
https://github.com/pksunkara/octonode/blob/master/src/octonode/client.coffee#L116-L122

For example,

```coffee script
github = require('octonode')
token =
  username: process.env.HUBOT_USER
  password: process.env.GITHUB_TOKEN
options = 
  ostname: 'ghe.example.com/api/v3'
client = github.client token, options
```

**Comment by pksunkara** [comment]
Thanks @uny :smile:

**Comment by ResidentBiscuit** [comment]
This should be documented.
