### ISSUE TITLE
typeof cbOrOptions === 'hash' prevents use of options in commit calls

### ISSUE THREAD

**Issue by GeorgePhillips** [pksunkara/octonode#209]
`/lib/octonode/repo.js` contains a instances of `typeof cbOrOptions === 'hash'`. passing an object will never evaluate to 'hash' but will return 'object'.

Changing it to `typeof cbOrOptions === 'object'` fixes the issue.

**Comment by pksunkara** [comment]
We are working on fixing it in #203

**Comment by GeorgePhillips** [comment]
#210

**Comment by pksunkara** [comment]
Or that could work too :smile:

**Comment by GeorgePhillips** [comment]
Easiest pull request ever. Can we get a version bump?

**Comment by pksunkara** [comment]
Done.

**Comment by GeorgePhillips** [comment]
Legend
