### ISSUE TITLE
Default Octonode user agent is not updated to package version

### ISSUE THREAD

**Issue by jeffwilcox** [pksunkara/octonode#212]
Hi,
FYI, the client's requests are still going out with a hardcoded version value by default, per https://github.com/pksunkara/octonode/blob/master/src/octonode/client.coffee#L38

Would be great for this to be dynamic.

**Comment by pksunkara** [comment]
Would love a PR. :)

**Comment by pksunkara** [comment]
Closed by https://github.com/pksunkara/octonode/commit/6d7cf2314491b21648c502e64f321d25b60e8799
