### ISSUE TITLE
Specify header when getting pull request

### ISSUE THREAD

**Issue by sungwoncho** [pksunkara/octonode#224]
I would like to specify header when getting a single pull request so that I can receive diff text.

It would look something like the following: 

```
ghpr.info({headers: {'Accept': 'application/vnd.github.VERSION.diff'}}, callback);
```

But currently octonode does not support it. Is there an undocumented way?

**Comment by pksunkara** [comment]
Unfortunately, You cannot directly do it like that but if you go through the base `client.coffee` file [here](https://github.com/pksunkara/octonode/blob/master/src/octonode/client.coffee), you can construct what you want easily. Thanks.

**Comment by sungwoncho** [comment]
Thanks for the reply. Closing this.
