### ISSUE TITLE
ghrepo.labels doesn't work with pagination signature as defined in docs

### ISSUE THREAD

**Issue by ggoforth** [pksunkara/octonode#230]
My implementation is below.  In my case I had `LABELS_PER_REQUEST` set to 100.  Running this call yields an empty array for labels in all cases.  I tried lowering the `LABELS_PER_REQUEST` to something lower and still nothing.  Removing it provides the labels.  

```
function getRepoLabels(req, res, next) {
  const client = github.gh(req.user.accessToken),
    org = req.params.org,
    repo = req.params.repo,
    ghrepo = client.repo(`${org}/${repo}`);

  ghrepo.labels(LABELS_PER_REQUEST, (err, labels) => {
    if (err) return next(new restify.errors.InternalError(err.message));
    console.log(labels);
    res.json({labels});
  });
}
```

**Comment by pksunkara** [comment]
@ggoforth You should set the `page` value if you want to set the `per_page`.

```js
ghrepo.labels(1, LABELS_PER_REQUEST, (err, labels) => {
});
```

Or you could give an object containing `per_page` key.

```js
ghrepo.labels({per_page: LABELS_PER_REQUEST}, (err, labels) => {
});
```

**Comment by ScottChapman** [comment]
This doesn't appear to be working for me. I have some 400+ labels, and I always only get 100 regardless of how I pass along pagination...

**Comment by pksunkara** [comment]
So, you are saying that github is not returning them properly?

**Comment by ScottChapman** [comment]
hmmm... yea I guess so? Just wondering if you are experiencing different results.

I am running it against our hosted github enterprise. Maybe it's an issue there?
