### ISSUE TITLE
team access logs api

### ISSUE THREAD

**Issue by arieljake** [pksunkara/octonode#235]
Not sure where this would go:
https://api.slack.com/methods/team.accessLogs

Please advise @pksunkara and I can file a PR.

**Comment by pksunkara** [comment]
@arieljake What is this issue about? You pointed to slack API docs.

**Comment by arieljake** [comment]
There is an api for pulling team access logs that is missing as far as I can tell in octonode. I'd like to add it. Where do you think the api belongs?

**Comment by gabrielcsapo** [comment]
@arieljake is this in relation to github?

**Comment by arieljake** [comment]
Omg! Sorry guys. Just spaced out a bit.
