### ISSUE TITLE
Return compiled data

### ISSUE THREAD

**Issue by sebastianjonasson** [pksunkara/octonode#239]
Would you consider a patch where e.g. repos would be included when calling ghuser.info.

What I'm thinking is something like

``` js
ghuser.info(callback); //normal behaviour

//include repos
var options = {
  includeRepos: true
}
ghuser.info(options, callback); 
```

Where the response would look something like:

``` json
{
  "login":"sebastianjonasson",
    ...
  "repos": [
    ...
  ]
}
```

**Comment by pksunkara** [comment]
Why is this needed? Since it involves calling 2 different endpoints, I don't like to merge them together even if the merge is happening behind an option.
