### ISSUE TITLE
Do you plan to integrate listing all organisations / users / repos 

### ISSUE THREAD

**Issue by mebjas** [pksunkara/octonode#241]
I recently had a use-case where I needed to list all orgs. So I modified the library as per my need.
In case you are planning to integrate that feature I shall send a pull request. 

The reason I dint send a pull directly is, I'd like to know how'd you like to modify `client.buildUrl` method, as `/organizations` api responds to `since` parameter for pagination rather than `page` parameter.

**Comment by pksunkara** [comment]
If you can send a PR first, I can review it and suggest any modifications. Thanks.

**Comment by mebjas** [comment]
Cool!
Tell me this, do you think it's better to have a separate API for this as adding it to Orgs class doesn't make sense, as it doesn't belong to instance of any org. Or we can have a separate Class for all global values like `organizations`, `users`

**Comment by pksunkara** [comment]
Improve the build_url to support `since` and people can do `client.get('/organizations')` etc.. We don't need to add methods for them.

**Comment by mebjas** [comment]
make sense.

**Comment by mebjas** [comment]
Implemented with https://github.com/pksunkara/octonode/pull/242
