### ISSUE TITLE
How to open a new public gist?

### ISSUE THREAD

**Issue by Thatkookooguy** [pksunkara/octonode#243]
I saw your api, and I see a way to create a gist:
```javascript
ghgist.create({
  description: "the description",
  files: { ... }
}), callback); //gist
```

but how do you set if that gist will be public or secret?

is the default `create` command creates a secret or a public one?

thanks!

**Comment by pksunkara** [comment]
You should give option `public: true` along with `description` and `files`.

**Comment by Thatkookooguy** [comment]
cool. thanks!
