### ISSUE TITLE
Shouldn't GET /user/repos return all my repositories?

### ISSUE THREAD

**Issue by imujjwal96** [pksunkara/octonode#246]
> client.get('/user/repos', {}, function (err, status, body, headers) {
  console.log(body);
});

> client.me().repos(function(err, body) {
    console.log(body);
});

Both these does not return all my repositories. Rather what they return are the Repositories of the organizations I am part of. I don't know whether it is a bug or a feature, but i would like to get all my repositories from my token or my keys.

**Comment by pksunkara** [comment]
Please make sure you have the correct token. I just confirmed that we still get the correct repos.

**Comment by imujjwal96** [comment]
I created a token with these permissions and yet i get only the repositories of the organizations. By the way I am using version 0.7.6

![untitled](https://cloud.githubusercontent.com/assets/8245662/18231018/24651e92-72ca-11e6-8292-aaa69a0afeb2.png)

**Comment by imujjwal96** [comment]
ok. So the mistake was from my side. I didn't realize that the following get request shows only a certain amount of repositories and by chance (or due to some belief) were of the organizations that I am part of. So I dug through the documentation and found something called pagination which solved my problem
