### ISSUE TITLE
Two Factor auth validation failed

### ISSUE THREAD

**Issue by chasevida** [pksunkara/octonode#250]
Hi there, I've been trying to [authenticate for a desktop cli](https://github.com/pksunkara/octonode#authentication) but have been running into a validation issue (shown below the request) when using the below code snippet.

**Reproduce Issue:**
1. Ensure you have two-factor auth setup on Github
2. Run the code snippet below without the `opt` key, value pair
3. A OPT code is generated and received
3. Run the code snippet below with the new OPT code
4. Returns an error `Validation Failed`, see further below the code snippet for the truncated exact error message.

Any help would be greatly appreciated.

**Auth Request:**
```
const Github = require('octonode')

Github.auth.config({
  username: '<USERNAME>',
  password: '<PASSWORD>',
  otp: '<OTP_CODE>'
}).login(['user', 'repo'], (err, id, token) => {

  if (err) {
    console.log(err)
  }
  else {
    console.log(id, token)
  }
})
```

**Auth Errors:**

[Validation Error L90](https://github.com/pksunkara/octonode/blob/master/lib/octonode/auth.js#L90)
```
Error: Validation Failed
    at Request._callback (/.../node_modules/octonode/lib/octonode/auth.js:90:31)
```

[Two-Factor Auth Error L97](https://github.com/pksunkara/octonode/blob/master/lib/octonode/auth.js#L97) is thrown for subsequent requests with the OTP which makes me think it was received at Github's end but maybe not handled correctly the first time? 
```
Error: Must specify two-factor authentication OTP code.
    at Request._callback (/.../node_modules/octonode/lib/octonode/auth.js:97:31)
```

I see there was #80 (allow passing One Time Password to login) but I can't find any tests to run to validate if it's just me experiencing this.

**Comment by pksunkara** [comment]
OTP expires so that 2FA errors of subsequent requests make sense. The first request is probably failing because you don't have any `note` that is being sent to the authorisations API. Apparently, it's now required. Can you try doing that and report back?

**Comment by chasevida** [comment]
Thanks @pksunkara that worked, really appreciate the quick response and pointing me in the right direction. Would you want a PR to update some of the docs to account for this? Changing the format for scopes to an `object` and adding the `note` works fine.

For those who stumble in after me, this was the solution:

```
const Github = require('octonode')

const scopes = {
  "add_scopes": [
    "user",
    "repo"
  ],
  "note": "admin script"
}

Github.auth.config({
  username: '<USERNAME>',
  password: '<PASSWORD>',
  otp: '<OTP_CODE>'
}).login(scopes, (err, id, token) => {

  if (err) {
    console.log(err)
  }
  else {
    console.log(id, token)
  }
})
```

**Comment by pksunkara** [comment]
Yes, I would appreciate if you could make a documentation PR. Thanks.
