### ISSUE TITLE
Is there an end-to-end example?

### ISSUE THREAD

**Issue by dewolfe001** [pksunkara/octonode#252]
In trying to use octonode to create a repo, I was looking for an end-to-end implementation of the process (authorization, repo creation, the result data from github). I see interactive examples with a web application, but I don't see one where the process is happening inside of one process.
What I've seen happen with my code base:
- it loads the octonode module
- it creates a github and client
- it tries to create a repo but it fails because it doesn't have authorization and it appears that the user/repo call happens before the client can be created and return an authorization token.
- I eventually tried to put in timeouts to give the authorization step a breather before it was used. That didn't make a difference. 

My code:

```
console.log('Hello World');

var lj = require('longjohn');
var util = require('util');
var github = require('octonode');

var url = 'api.github.com';
var user = ''; // was filled out
var secret = ''; // was filled out

var nom = 'December Test';
var descrip = 'This is a test of how node.js uses http to create a repo.';

console.log('line 20');
var client = github.client({
  id: user,
  secret: secret
});

setTimeout(function () {
	console.log('line 26 ' + util.inspect(client));

	client.get('/user', {}, function (err, status, body, headers) {
		if (err) {
			console.log('line 28 ' + util.inspect(err));	
		}
		else {	
			console.log('line 31 ' + util.inspect(body));
		}
	});
}, 1000);	

setTimeout(function () {
	console.log('line 35');
	var ghme = client.me();

	ghme.info(function(err, data, headers) {
		console.log("error: " + err);
		console.log("data: " + data);
		console.log("headers:" + headers);
	});

	console.log('line 54');
	var repo = ghme.repo({
	  'name': nom,
	  'description': descrip,
	}, function(err, data) {
		if (err) {
			console.log('line 60 ' + util.inspect(err));	
		}
		else {	
			console.log('line 63 ' + util.inspect(data));
		}
	}); //repo made

	console.log('line 67');
}, 1000);
```

**Comment by pksunkara** [comment]
Here is a sample script using octonode. https://gist.github.com/pksunkara/7981618
