### ISSUE TITLE
possibility to cache results?

### ISSUE THREAD

**Issue by gabrielcsapo** [pksunkara/octonode#261]
Would you be interested in adding a feature that caches calls. The client could have a cache timeout that could invalidate after a certain amount of time and would then call the route if it expires.

```javascript
const github = require('octonode');
const client = Github.client(process.env.GITHUB_TOKEN, {
  hostname: 'github.com/api/v3',
  cacheTimeout: 36000 // time in MS
});
```

**Comment by pksunkara** [comment]
@gabrielcsapo How would this work?

**Comment by gabrielcsapo** [comment]
@pksunkara we could use something like https://github.com/ptarjan/node-cache which everytime a get request is made we can store the results in memory and when the get request is called again we can directly use the in memory cache.

**Comment by pksunkara** [comment]
I think that is something that should be done outside the API Client.

**Comment by gabrielcsapo** [comment]
The http module has a cache property where it holds content if the parameters are the same, should it not be the case for this? If I call octonode shouldn't it give me the results if some other piece of code has called the same function a couple seconds earlier?

**Comment by pksunkara** [comment]
That would work then. Please go ahead with the implementation and make a PR.

**Comment by gabrielcsapo** [comment]
@pksunkara would you mind opening this up under your name, I have moved to node-github for the features and don't want to keep this issue open any longer

**Comment by pksunkara** [comment]
You can unsubscribe from the issue.
