### ISSUE TITLE
Pass headers to individual requests

### ISSUE THREAD

**Issue by kbariotis** [pksunkara/octonode#266]
This API should be able to accept headers on individual requests. E.g. the `If-None-Match` header to the `github.repo().issues()` as described [here](https://developer.github.com/guides/getting-started/#conditional-requests).

Thank you

PS: I guess this is the same with #201

**Comment by pksunkara** [comment]
I would welcome any contribution. Unfortunately, I do not have the time to work on this issue.

**Comment by kbariotis** [comment]
Since you have such a declarative API I would suggest doing something like this:

`github.repo().conditional('ETAG').issues()`

This will add the `If-None-Match` header to the `issues` request.

What do you think @pksunkara ?

**Comment by pksunkara** [comment]
Looks okay. Will be waiting for a PR. 😄

**Comment by JacopoDaeli** [comment]
@pksunkara https://github.com/pksunkara/octonode/pull/291
What do you think?

**Comment by pksunkara** [comment]
Done with 0.9.0

**Comment by JacopoDaeli** [comment]
@pksunkara we bum do 0.9.0 finally?

**Comment by JacopoDaeli** [comment]
👍 Let me know when you publish on NPM.

**Comment by pksunkara** [comment]
Done.
