### ISSUE TITLE
Projects API

### ISSUE THREAD

**Issue by tborychowski** [pksunkara/octonode#267]
Are you planning to include the [Projects API](https://developer.github.com/v3/projects/)?

**Comment by pksunkara** [comment]
I would welcome any PRs.

**Comment by tborychowski** [comment]
I'd like to try, but I'm having some problems with tests:
```
create release
    ✗ should create a release with tag v1.0.0 
      TypeError: Cannot read property 'tag_name' of undefined 
      at Object.should create a release with tag v1.0.0 (/Projects/octonode/test/release/index.js:32:23) 
```

**Comment by pksunkara** [comment]
I haven't actually maintained tests for a long time. I am not sure they even work. It's hard to test client libraries.

**Comment by tborychowski** [comment]
Ok. I will ignore them :-)

**Comment by tborychowski** [comment]
here's the PR: https://github.com/pksunkara/octonode/pull/268
Please have a look and maybe see if I haven't missed anything.

**Comment by pksunkara** [comment]
Release 0.7.10

**Comment by tborychowski** [comment]
Thanks!
