### ISSUE TITLE
Discussion: Bot which listens to mentions on PR

### ISSUE THREAD

**Issue by hemangsk** [pksunkara/octonode#269]
Hey @pksunkara  ! First off thanks a ton for creating this wonderful utility, I'm learning Coffeescript and node.js GitHub API and this is helping me in infinite ways!

I have a little query, and it'd be really awesome if you can give me some directions on how to proceed.
Actually I am trying to create a bot which listens to Pull Request Mentions. So primarily, When that bot is mentioned by anyone on GitHub in their Pull Request, the bot would perform some tasks and comment on that PR. Like rultor does, but with node.js.

I'm thinking if I authenticate the user with node.js GitHub API, and then get notifications of that user after every specified interval of time. Once I run the program, it perfectly returns the JSON responses and ends, But the issue is, ideally the bot must stay awake and keep looking for more notifications (for notification events). I'm not able to figure out how can I keep waiting for notification events, any help or pointers would be really really awesome! 😃 
 
Thanks a ton!

Here's the notification fetching code which I'm using powered by octonode,
```
var github = require('octonode');

var client = github.client('token');

client.get('/user', {}, function (err, status, body, headers) {
  console.log('\n');
  console.log(body); //json object
});


var ghme = client.me();

ghme.notifications({}, function (err, status, body, headers){
  console.log("Notifications");
  console.log(body);
});
```

**Comment by pksunkara** [comment]
You will have to use `setTimeout` feature of node.js. This is more of a node.js question and I would appreciate if you use the appropriate forums for that question instead of this repo. Thanks.
