### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by tueric** [pksunkara/octonode#274]
When I try to use the createComment function on issues, I get "Validation Failed", even though I have enabled all permissions on my token. I am able to merge pull requests and everything too. 

Thanks

**Comment by pksunkara** [comment]
What is the request body you are sending? Are other functions working?

**Comment by tueric** [comment]
```ghissue.createComment({
            body: `TEST`
          },(commentErr, commentRes) => {
            if(commentErr){
              console.log (`COMMENT ERROR ${commentErr}`);
              return;
            }
            console.log(`Comment Success! ${commentRes}`);
          });```
That is the request I am sending. I tried using the issue api because the pull request api was giving me the same validation failed error. But yes, other functions work. I'm able to merge pull requests, and get comments on pull requests/issues.

**Comment by pksunkara** [comment]
Can you screenshot the permissions on github?

**Comment by Dinodanio** [comment]
Same here on pull_requests

```
ghclient.pr(api_url, project.pull_request).createComment({
            body: msg_body,
            commit_id: msg_hash,
            path: '',
            position: 0
        }, callback => {
            console.log(callback)
        })
```

**Comment by pksunkara** [comment]
I can't help without extra information people.

**Comment by jwindmuller** [comment]
Maybe this helps future people.

I was having this error during login `octonode.auth.config(config).login(...)`, it stopped as soon as I deleted the existing token for my app.

Now I have a custom error message to handle this case.
