### ISSUE TITLE
Client -> me -> issues return 404

### ISSUE THREAD

**Issue by saadanjum** [pksunkara/octonode#275]
I am getting a 404 from the github api
`GET https://api.github.com/user/issues 404 (Not Found)`

Here is my test case
```
const client = github.client('some-token');
const ghme = client.me();
ghme.issues((err, data) => {
    console.log(data);
});
```

Following: https://github.com/pksunkara/octonode#list-all-issues-across-owned-and-member-repositories-get-userissues

**Comment by saadanjum** [comment]
I guess nobody cares about this :) Closing.

**Comment by pksunkara** [comment]
@saadanjum Did it work you? I got it working, so I am not sure what the issue was. Meant to reply but forgot.
