### ISSUE TITLE
org level events

### ISSUE THREAD

**Issue by gabrielcsapo** [pksunkara/octonode#279]
Would it be a good addition to get org level events?

```
https://developer.github.com/v3/activity/events/#list-public-events-for-an-organization
```

```
List public events for an organization
GET /orgs/:org/events
```

**Comment by pksunkara** [comment]
A PR is always welcome.

**Comment by gabrielcsapo** [comment]
@pksunkara would you mind opening this up under your name, I have moved to node-github for the features and don't want to keep this issue open any longer

**Comment by pksunkara** [comment]
You can unsubscribe from the issue.
