### ISSUE TITLE
Caching the results

### ISSUE THREAD

**Issue by pksunkara** [pksunkara/octonode#282]
#261

**Comment by jeffpearce** [comment]
@pksunkara have you started working on this? We need to be able to control caching as well. I'm willing to look at it if it's not in progress

**Comment by pksunkara** [comment]
@jeffpearce You are welcome to do it.

**Comment by jeffpearce** [comment]
Slightly different solution #291

**Comment by pksunkara** [comment]
Done with 0.9.0
