### ISSUE TITLE
Getting this error:  Uncaught ReferenceError: Project is not defined

### ISSUE THREAD

**Issue by ameshkin** [pksunkara/octonode#293]
Hi there,

We are working on a way to reward open source developers.  We're using your API to connect to git but we're having a problem.

We keep getting this error when trying to access a project
 Uncaught ReferenceError: Project is not defined

The code which causes this problem is :  var ghproject      = client.project('pamtoken/test_platform', 1);

It doesn't work with the default user either.

**Comment by pksunkara** [comment]
We have release 0.9.0 which uses promises.

**Comment by pksunkara** [comment]
Fixed by #324
