### ISSUE TITLE
Cannot get starred repositories

### ISSUE THREAD

**Issue by mustafagonul** [pksunkara/octonode#300]
I am using this piece of code to retrieve the starred repositories of the user

```
const { GitHubApi } = require('octonode');
const { URL, URLSearchParams } = require('url');

class GitHub {
  constructor(token = null) {
    this.api = require('octonode');
    this.token = token;

    this.url = this.api.auth.config({
      id: '*******',
      secret: '*******',
      apiUrl: 'https://github.com/api/v3',
      webUrl: 'https://github.com'
    })
    .login(['user', 'public_repo', 'repo'], data => console.log(data));
  }

  code(url) {
    const u = new URL(url, 'http://localhost:8080');

    return u.searchParams.get('code');
  }

  state(url) {
    const u = new URL(url, 'http://localhost:8080');

    return u.searchParams.get('state');
  }

  login(code) {
    this.api.auth.login(code, (error, token, headers) => {
      console.log(error);
      console.log(token);
      console.log(headers);

      if (error) {
        console.log(error);

        this.token = null;

        return;
      }

      if (token) {
        console.log(token);

        this.token = token;

        this.me();

        return;
      }
    });
  }

  me() {
    const client = this.api.client(this.token);
    const ghme = client.me();

    const callback = (error, data, headers) => {
      console.log("error:", error);
      console.log("data:", data);
      console.log("headers:", headers);
    }

    // ghme.info(callback);

    ghme.starred(callback);

  }
}

module.exports = new GitHub();

```

I can get info of the authenticated user successfully but I get following error for starred.

```
error: { [Error: Not Found]
  message: 'Not Found',
  statusCode: 404,
  headers: 
   { server: 'GitHub.com',
     date: 'Sun, 10 Dec 2017 21:50:08 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '128',
     connection: 'close',
     status: '404 Not Found',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4983',
     'x-ratelimit-reset': '1512942647',
     'x-oauth-scopes': '',
     'x-accepted-oauth-scopes': 'repo',
     'x-oauth-client-id': 'Iv1.8a33c91c340acf7e',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'access-control-allow-origin': '*',
     'content-security-policy': 'default-src \'none\'',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-xss-protection': '1; mode=block',
     'x-runtime-rack': '0.041083',
     'x-github-request-id': 'D22C:15B0:3142B9:63F16B:5A2DAC0F' },
  body: 
   { message: 'Not Found',
     documentation_url: 'https://developer.github.com/v3/activity/starring/#list-repositories-being-starred' } }
data: undefined
headers: undefined
```

**Comment by pksunkara** [comment]
What happens with the `ghme.info`?

**Comment by mustafagonul** [comment]
I can successfully use `ghme.info`. I can get the user data of the authenticated user. (status code = 200, login, id, email, ...) But when I tried to use `ghme.starred`, I get the error below.

**Comment by pksunkara** [comment]
I have no idea what's happening here. Can you find out which URL it is calling?

**Comment by mustafagonul** [comment]
error: null
data: { login: 'mustafagonul',
  id: 1651913,
  avatar_url: 'https://avatars3.githubusercontent.com/u/1651913?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mustafagonul',
  html_url: 'https://github.com/mustafagonul',
  followers_url: 'https://api.github.com/users/mustafagonul/followers',
  following_url: 'https://api.github.com/users/mustafagonul/following{/other_user}',
  gists_url: 'https://api.github.com/users/mustafagonul/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mustafagonul/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mustafagonul/subscriptions',
  organizations_url: 'https://api.github.com/users/mustafagonul/orgs',
  repos_url: 'https://api.github.com/users/mustafagonul/repos',
  events_url: 'https://api.github.com/users/mustafagonul/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mustafagonul/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mustafa Gönül',
  company: null,
  blog: 'http://www.mustafagonul.com',
  location: 'Istanbul',
  email: 'mustafagonul@gmail.com',
  hireable: true,
  bio: null,
  public_repos: 14,
  public_gists: 0,
  followers: 11,
  following: 28,
  created_at: '2012-04-17T13:44:58Z',
  updated_at: '2017-12-12T13:02:41Z' }
headers: { server: 'GitHub.com',
  date: 'Tue, 12 Dec 2017 21:47:16 GMT',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '1217',
  connection: 'close',
  status: '200 OK',
  'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4996',
  'x-ratelimit-reset': '1513118563',
  'cache-control': 'private, max-age=60, s-maxage=60',
  vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
  etag: '"dd348be8a737d8234dc273bace0829a0"',
  'last-modified': 'Tue, 12 Dec 2017 13:02:41 GMT',
  'x-oauth-scopes': '',
  'x-accepted-oauth-scopes': '',
  'x-oauth-client-id': 'Iv1.8a33c91c340acf7e',
  'x-github-media-type': 'github.v3; format=json',
  'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
  'access-control-allow-origin': '*',
  'content-security-policy': 'default-src \'none\'',
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'deny',
  'x-xss-protection': '1; mode=block',
  'x-runtime-rack': '0.042650',
  'x-github-request-id': '81FA:791B:A9219D:18BA92A:5A304E63' }

**Comment by mustafagonul** [comment]
I had created Github App instead of OAuth App. That was the reason I could not use the API for authorized user.
