### ISSUE TITLE
Listing comments for a repository

### ISSUE THREAD

**Issue by alextreppass** [pksunkara/octonode#309]
Hi, it is possible to enumerate through comments as per https://developer.github.com/v3/repos/comments/#list-commit-comments-for-a-repository

Context: am looking for a way to categorise the types of PR comments that appear on different file types, and currently have to enumerate through pull requests from `#1` upwards.

If there's an easier way to do it please let me know!

Thanks

**Comment by pksunkara** [comment]
It depends on your use case. You should be ideally using this, https://developer.github.com/v3/repos/comments/#list-comments-for-a-single-commit but if you need to get comments for all commits in repo, iteration is the only way.

**Comment by alextreppass** [comment]
Hi @pksunkara from my link above it looks like I should be able to do `GET /repos/:owner/:repo/comments` and then paginate. I'm not sure how to do this with octonode though
