### ISSUE TITLE
creating branch

### ISSUE THREAD

**Issue by GlauberF** [pksunkara/octonode#312]
The documentation is a bit confusing, as I do to create a new branch, I could comment with an example.
Authenticating and then creating the branch?

**Comment by pksunkara** [comment]
I dont understand what you are asking. Can you elaborate?

**Comment by GlauberF** [comment]
por exemplo nese exemplo `ghrepo.merge({ base: baseBranch, head: destinationBranch }, callback)` você compara duas branches, a **baseBranch** com a **destinationBranch**.

Minha pergunta, como faço para criar por exemplo a branch **destinationBranch** a partir da branch **master** ?

**Comment by pksunkara** [comment]
It's not supported yet.

**Comment by mikiec84** [comment]
hhjkj
