### ISSUE TITLE
Is not listing branches from my private repository

### ISSUE THREAD

**Issue by GlauberF** [pksunkara/octonode#313]
## code:

![captura de tela de 2018-06-13 08-40-10](https://user-images.githubusercontent.com/11314585/41348908-841d4e1e-6ee4-11e8-8a70-062f71872020.png)

## return: null
![captura de tela de 2018-06-13 08-40-30](https://user-images.githubusercontent.com/11314585/41348924-965a3542-6ee4-11e8-8ec2-11ee7d508c42.png)

if the way I'm doing is wrong, leave the comments the right way :)
I will replicate in my code

**Comment by pksunkara** [comment]
The first argument is the error. You need to do something like this:

```
ghrepo.branches( (err, rep) => {
  console.log(rep);
});
```
