### ISSUE TITLE
Mention Promise / async support in the README

### ISSUE THREAD

**Issue by Rycochet** [pksunkara/octonode#314]
Looking into using this and wanted Promise support, but it's only really mentioned via the PR #286 and original (closed) issue #139 

Would be useful if they were referenced in the readme so it's easier to find out about ;-)

**Comment by pksunkara** [comment]
Would welcome a pr

Pavan Kumar Sunkara

**Comment by Circuit8** [comment]
I found the same issue, here is the PR: #320
