### ISSUE TITLE
OAuth authentication will be discontinued at the end of June, 2020

### ISSUE THREAD

**Issue by BanzaiMan** [pksunkara/octonode#338]
I've received email from GitHub regarding the use of an deprecated API:

<blockquote>
On February 10th, 2020 at 19:18 (UTC) your personal access token (********) using octonode/0.3 (https://github.com/pksunkara/octonode) terminal/0.0 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/NNNNNNNN/deployments

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
</blockquote>

Looking at the source code, it does appear that octonode is using `POST /authorizations`.
https://github.com/pksunkara/octonode/blob/v0.9.5/src/octonode/auth.coffee#L52-L58

Could you take a look at replacing this call?

Thanks!

**Comment by pksunkara** [comment]
This is only affecting the CLI mode. I am willing to take a PR. Otherwise, it will take a bit of time for me.

**Comment by arrudaricardo** [comment]
@pksunkara can I work on this issue?

**Comment by pksunkara** [comment]
@arrudaricardo Please go ahead

**Comment by petervtzand** [comment]
Hi, @arrudaricardo  any progress on this?

**Comment by thomasmalbaux** [comment]
If I'm not mistaken, GitHub communicated few months ago that this deprecation will actually happen in September 2020, with brownouts in late September and October.

See https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

So this still is happening, but the July 1st 2020 timeline has been extended a bit.

**Comment by Antoninbln** [comment]
Hi 👋
Is there any progress in the issue ?

**Comment by thomasmalbaux** [comment]
At least there has been some changes at GitHub: the deadline has changed again and is now in May 2021 (with brownouts in March and April). Deadline is no longer in September 2020. See https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/.

**Comment by SungHyeon-Kim1** [comment]
@pksunkara 
Is octonode not related to the URL below?
[https://developer.github.com/changes/2020-02-14-deprecating-password-auth/](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/)

Its deadline is November 13th, 2020, is that okay?

**Comment by pksunkara** [comment]
Okay guys, I looked into this quite a bit and I can say that there is nothing that can be done on my library side to fix your issues.

1. If you are using CLI flow with username and password, then please switch to constructing your client using either the access token or use the `web` mode for `auth` to prompt the end user to get one (because they removed the authorizations endpoint)
2. If you are using username and password directly for client, you need to switch (because they deprecated password auth)
3. If you are using client id and secret directly for client, you need to switch (because they removed support for authentication using query params)

**Comment by petervtzand** [comment]
Hi @pksunkara, sorry for the late response.
What do you mean with option 3: 'You need to switch'. Do you mean switch away from Octonode?

So If I get this correc: When using an access token, Octonode **cannot** connect with Github using authentication in the headers, but only authentication through query parameters?

**Comment by petervtzand** [comment]
Thanks! The library I used (https://github.com/atmos/hubot-deploy), used a very old version of Octonode. Created a fork and updated Octonode. Everything works now.

So just to be clear for others, Octonode **does** supports authentication via authentication headers when using a secret token. Even better I think the current version **only** supports that?
