### ISSUE TITLE
Find another user's repositories

### ISSUE THREAD

**Issue by francoZuniga32** [pksunkara/octonode#344]
Hi, I wanted to know if there is a way to search the repositories of another user. Try with:
```javascript
var ghuser = client.user('Erick-2727');
     ghuser.repos((body) => {
     console.log(body);
});
```
donde _client_ es un usuario creado con:
```javascript
const github = require('octonode');
client = github.client(token);
```
if you could give me help it would be great

**Comment by pksunkara** [comment]
`ghuser.repos` is the correct way to do it. I can't help you if you don't print the errors you are getting.
