### ISSUE TITLE
suggest open rate limit's reset value

### ISSUE THREAD

**Issue by yanghua** [pksunkara/octonode#52]
Think about this demand:when my remaining(left) is "0" . Then I will use sleep(n) to block the current running until the left reset to max. I can get the "n" from the reset value. The offical api:http://developer.github.com/v3/rate_limit/  thanks!

**Comment by jeffwilcox** [comment]
The information about rate limit remaining, as well as the reset time, is all provided in the `headers` (3rd param) in the callbacks for all of the methods inside of the octonode library.

You can use this to implement whatever app-side logic you want to work beyond that limit. What specifically is this issue for, given the exposed values?

Example subset of the `headers` returned; you can use `x-ratelimit-reset` to write your logic...

```
 'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4949',
  'x-ratelimit-reset': '1424977658',
```

**Comment by arieljake** [comment]
@pksunkara can we close this issue?
