### ISSUE TITLE
fetch all users support

### ISSUE THREAD

**Issue by yanghua** [pksunkara/octonode#55]
> http://developer.github.com/v3/users/#get-all-users

**Comment by jeffwilcox** [comment]
You should be able to implement this using the client within the library.

You'll still need to do some work using the 3rd parameter returned by the callback, `headers`, to detect and continue traversing through the pages in a smart manner, plus you'll have to work hard to batch these in a useful way to get through the list using page/per_page, etc.

**Comment by arieljake** [comment]
@pksunkara can we close this issue?
